# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'inicio.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 400)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.background_inicio = QtWidgets.QLabel(self.centralwidget)
        self.background_inicio.setGeometry(QtCore.QRect(0, 0, 701, 401))
        self.background_inicio.setStyleSheet("background-image: url(:/fon_ini/Welcome.png);")
        self.background_inicio.setText("")
        self.background_inicio.setPixmap(QtGui.QPixmap("../img/Welcome.png"))
        self.background_inicio.setScaledContents(True)
        self.background_inicio.setObjectName("background_inicio")
        self.button_Inicio = QtWidgets.QPushButton(self.centralwidget)
        self.button_Inicio.setGeometry(QtCore.QRect(280, 260, 141, 41))
        self.button_Inicio.setStyleSheet("/* Estilo base del botón */\n"
"QPushButton {\n"
"    background-color: green; /* Fondo verde */\n"
"    color: white; /* Texto blanco */\n"
"    border: none; /* Sin borde */\n"
"    padding: 10px 20px; /* Relleno */\n"
"    font-size: 18px; /* Tamaño de fuente */\n"
"}\n"
"\n"
"/* Estilo para el hover */\n"
"QPushButton:hover {\n"
"    background-color: darkgreen; /* Cambia el fondo a verde oscuro */\n"
"    border-bottom: 3px solid black; /* Añade un borde inferior negro */\n"
"}\n"
"")
        self.button_Inicio.setObjectName("button_Inicio")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.button_Inicio.setText(_translate("MainWindow", "INICIAR"))
import Inicio_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
