# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'slot.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Game_visual(object):
    def setupUi(self, Game_visual):
        Game_visual.setObjectName("Game_visual")
        Game_visual.resize(644, 423)
        self.game = QtWidgets.QOpenGLWidget(Game_visual)
        self.game.setGeometry(QtCore.QRect(50, 80, 391, 231))
        self.game.setObjectName("game")
        self.button_Recarga = QtWidgets.QPushButton(Game_visual)
        self.button_Recarga.setGeometry(QtCore.QRect(30, 10, 141, 51))
        self.button_Recarga.setStyleSheet("QPushButton:pressed {\n"
"    background-color: #555;\n"
"    border-color: #333;\n"
"}\n"
"\n"
"QPushButton:pressed > QIcon {\n"
"    color: #000;\n"
"    filter: brightness(50%);\n"
"}\n"
"")
        self.button_Recarga.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../img/RECARGAR.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_Recarga.setIcon(icon)
        self.button_Recarga.setIconSize(QtCore.QSize(140, 48))
        self.button_Recarga.setObjectName("button_Recarga")
        self.lcdMonto = QtWidgets.QLCDNumber(Game_visual)
        self.lcdMonto.setGeometry(QtCore.QRect(30, 350, 141, 41))
        font = QtGui.QFont()
        font.setStrikeOut(False)
        self.lcdMonto.setFont(font)
        self.lcdMonto.setObjectName("lcdMonto")
        self.lcdApuesta = QtWidgets.QLCDNumber(Game_visual)
        self.lcdApuesta.setGeometry(QtCore.QRect(260, 350, 141, 41))
        font = QtGui.QFont()
        font.setStrikeOut(False)
        self.lcdApuesta.setFont(font)
        self.lcdApuesta.setObjectName("lcdApuesta")
        self.button_Go = QtWidgets.QLabel(Game_visual)
        self.button_Go.setGeometry(QtCore.QRect(0, 0, 651, 431))
        self.button_Go.setStyleSheet("background-image: url(:/newPrefix/background.qrc.jpg);")
        self.button_Go.setText("")
        self.button_Go.setPixmap(QtGui.QPixmap("../img/background.qrc.jpg"))
        self.button_Go.setScaledContents(True)
        self.button_Go.setObjectName("button_Go")
        self.lcdApuesta_2 = QtWidgets.QLCDNumber(Game_visual)
        self.lcdApuesta_2.setGeometry(QtCore.QRect(470, 350, 141, 41))
        font = QtGui.QFont()
        font.setStrikeOut(False)
        self.lcdApuesta_2.setFont(font)
        self.lcdApuesta_2.setObjectName("lcdApuesta_2")
        self.pushButton = QtWidgets.QPushButton(Game_visual)
        self.pushButton.setGeometry(QtCore.QRect(480, 180, 121, 51))
        self.pushButton.setObjectName("pushButton")
        self.button_Go.raise_()
        self.game.raise_()
        self.button_Recarga.raise_()
        self.lcdMonto.raise_()
        self.lcdApuesta.raise_()
        self.lcdApuesta_2.raise_()
        self.pushButton.raise_()

        self.retranslateUi(Game_visual)
        QtCore.QMetaObject.connectSlotsByName(Game_visual)

    def retranslateUi(self, Game_visual):
        _translate = QtCore.QCoreApplication.translate
        Game_visual.setWindowTitle(_translate("Game_visual", "Form"))
        self.pushButton.setText(_translate("Game_visual", "JUGAR"))
import fondo_rc
import test_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Game_visual = QtWidgets.QWidget()
    ui = Ui_Game_visual()
    ui.setupUi(Game_visual)
    Game_visual.show()
    sys.exit(app.exec_())
